openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of my contacts app
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://127.0.0.1:3000
  - url: https://nodejs-hw-mongodb-5-pwl1.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/pathscontacts/get.yaml
    post:
      $ref: ../swagger/pathscontacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/pathscontacts/{id}/get.yaml
    patch:
      $ref: ../swagger/pathscontacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/pathscontacts/{id}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
